#!/bin/bash
#
# Scripts de execução das linhas de comando Things
# O ambiente definido aqui será exportado para todas as aplicações lançadas
# -----
# É esperado que as shared libraries indiretamente carregadas a partir de uma execução da JVM estejam
# regularmente instaladas no sistema operacional. No entanto, é possível definir essa instalação
# pela variável LD_LIBRARY_PATH. As shared libraries carregadas diretamente pela JVM (System.loadLibrary())
# devem estar definidas na variável de ambiente Java apropriada nos arquivos de configuração da aplicação.
# Presentemente, são requeridas as shared libraries do cliente IBM MQSeries e do Oracle OCI
source $(dirname $0)/../../gtx-env
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
# -----
# As dependências Java requeridas para a execução do Bootstrap Things são apenas as que seguem.
# As demais são definidas nos arquivos de configuração correspondentes
HOME_DIR="$HOME/development/sefipx/things/docs"
JTHINGS_JAR="$CRYPTHINGS/dist/release/things-1.3.1.jar"
export JAVA_CLASS_PATH="$JDIGESTER_JAR:$JTHINGS_JAR"
export JAVA_HOME="$JAVA_HOME"
export PATH="$JAVA_HOME/jre/bin:$PATH"
export EXECUTION_DIR="$HOME_DIR"
export CONFIG_LOCATION="$HOME_DIR"
